sudo: required
services:
  - docker


before_install:
  - docker build -t girish0308/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true girish0308/docker-react npm run test -- --coverage
